# 数理科学概論 第2回
## 2023/4/22
## ベクトル


In [1]:
import numpy as np

## 演習問題
ベクトル
$$\vec{r} = \left( 
\begin{matrix}
0  \\
-100  \\
100
\end{matrix}
\right), ~~
\vec{g} = \left( 
\begin{matrix}
-50  \\
-100  \\
150
\end{matrix}
\right), ~~
\vec{n} = \left( 
\begin{matrix}
-5  \\
15  \\
-10
\end{matrix}
\right)$$
に対して、内積 $\vec{r} \cdot \vec{g}, ~~
\vec{g} \cdot \vec{n}, ~~
\vec{n} \cdot \vec{r}$ をそれぞれ求めよ。


In [2]:
# ベクトルは numpy array を使うと便利
r = np.array([0, -100, 100])
g = np.array([-50, -100, 150])
n = np.array([-5, 15, -10])

In [3]:
# 内積の計算
np.dot(r, g)

25000

In [4]:
np.dot(g, n)

-2750

In [5]:
np.dot(n, r)

-2500

In [6]:
# 内積は @ でも表記可能
r @ g

25000

In [7]:
# 成分計算しても求められる。
np.sum(r*g)

25000

##ベクトルの計算


In [8]:
# ベクトルの和
r+g

array([ -50, -200,  250])

In [9]:
# ベクトルの大きさ (ユークリッドノルム)
np.linalg.norm(r)

141.4213562373095

In [10]:
# ベクトルの大きさを成分から計算
np.sqrt(np.sum(r**2))

141.4213562373095

## ベクトル計算と統計量

偏差ベクトルに対して、データ数 (ベクトルの次元数) を $N$ とする。
- [ベクトルの大きさ]$^2/N =$ 分散

In [11]:
# [ベクトルの大きさ]の二乗/Nの計算
# Python では変数名の大文字と小文字は区別される
N = len(r)
np.linalg.norm(r)**2 / N

6666.666666666667

In [12]:
# ライブラリを使って分散を計算
np.var(r)

6666.666666666667

- 内積$/N =$ 共分散

In [13]:
# 内積/Nの計算
np.dot(r, g)/N

8333.333333333334

In [14]:
# ライブラリを使って共分散を計算。
# 単に共分散を求めるには bias=True のオプションを指定する。
# これを入れないと、デフォルトでは不偏共分散 (母集団の共分散の推定値) が算出される。
# 4つの出力のうち右上、左下が共分散。左上、右下は r, g の分散。
np.cov(r, g, bias=True)

array([[ 6666.66666667,  8333.33333333],
       [ 8333.33333333, 11666.66666667]])

- コサイン類似度 $=$ 相関係数

In [15]:
# g と n のコサイン類似度の計算。内積/[g の大きさ]/[n の大きさ]
np.dot(g, n)/np.linalg.norm(g)/np.linalg.norm(n)

-0.7857142857142857

In [16]:
# ライブラリで相関係数を計算。
# 4つの出力のうち右上、左下が相関係数。左上、右下は自分自身に対する相関係数 (なので常に1)。
np.corrcoef(g, n)

array([[ 1.        , -0.78571429],
       [-0.78571429,  1.        ]])